name: 'Pact Can I Deploy'
description: 'Checks if a Pact version can be deployed to a target environment.'
inputs:
  pact_broker_token:
    required: true
    description: 'Token for authenticating with the Pact Broker'
  artefact_version:
    required: true
    description: 'Version of the Pact artefact to check'
  pact_application_name:
    required: true
    description: 'Name of the Pact application (pact-icipant)'
  pact_broker_base_url:
    required: false
    description: 'Base URL of the Pact Broker'
    default: 'https://hmcts-dts.pactflow.io'
  pact_env:
    required: false
    description: 'Environment to check deployment for'
    default: 'dev/pactTest'

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Install Pact CLI
      shell: bash
      run: npm install -g @pact-foundation/pact-cli

    - name: Tag Version
      shell: bash
      run: |
        pact-broker create-version-tag \
          --pacticipant "${{ inputs.pact_application_name }}" \
          --version "${{ inputs.artefact_version }}" \
          --tag "${{ inputs.pact_env }}" \
          --broker-base-url "${{ inputs.pact_broker_base_url }}" \
          --broker-token "${{ inputs.pact_broker_token }}"

    - name: Can I Deploy
      shell: bash
      run: |
        pact-broker can-i-deploy \
          --pacticipant "${{ inputs.pact_application_name }}" \
          --version "${{ inputs.artefact_version }}" \
          --to-environment "${{ inputs.pact_env }}" \
          --broker-base-url "${{ inputs.pact_broker_base_url }}" \
          --broker-token "${{ inputs.pact_broker_token }}" \
          --output table
        can_i_deploy_status=$?
        if [ "$can_i_deploy_status" -ne 0 ]; then
          echo "❌ Can-I-Deploy failed — this version is NOT safe to deploy to ${{ inputs.pact_env }} - (deploy status: $can_i_deploy_status)"
          exit 1
        else
          echo "✅ Can-I-Deploy succeeded — this version is safe to deploy to ${{ inputs.pact_env }}"
        fi
